services:
    mariadb:
        container_name: mariadb
        image: mariadb
        build:
            context: requirements/mariadb/
        env_file: .env
        secrets:
            - db-password
            - db-root-password
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - inception
        restart: always

    wordpress:
        container_name: wordpress
        image: wordpress
        build:
            context: requirements/wordpress/
        depends_on:
            - mariadb
            - redis
        volumes:
            - wordpress_data:/var/www/html
        secrets:
            - db-password
            - wp-admin-password
        env_file: .env
        networks:
            - inception
        restart: always

    nginx:
        container_name: nginx
        image: nginx
        hostname: ${HOST_NAME}
        build:
            context: requirements/
            dockerfile: nginx/Dockerfile
        depends_on:
            - wordpress
        volumes:
            - wordpress_data:/var/www/html
        ports:
            - 443:443
            - "80:80"
            - "8080:8080"
            - "8081:8081"
            - "8082:8082"
        networks:
            - inception
        restart: always

    ####################### BONUS  #######################

    ftp:
        container_name: ftp
        image: ftp
        pull_policy: never
        build:
            context: requirements/bonus/vsftpd/
        depends_on:
            - wordpress
        volumes:
            - wordpress_data:/var/www/html
        ports:
            - "21:21"
            - "21100-21110:21100-21110"
        secrets:
            - ftp-password
        env_file: .env
        networks:
            - inception
        restart: always

    adminer:
        container_name: adminer
        image: adminer
        build:
            context: requirements/bonus/adminer/
        depends_on:
            - mariadb
        networks:
            - inception
        restart: always

    redis:
        container_name: redis
        image: redis
        build:
            context: requirements/bonus/redis/
        networks:
            - inception
        restart: always

    cadvisor:
        container_name: cadvisor
        pull_policy: never
        image: cadvisor
        build:
            context: requirements/bonus/cadvisor/
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        networks:
            - inception
        restart: always

secrets:
    db-password:
        file: secrets/db_password
    db-root-password:
        file: secrets/db_root_password
    wp-admin-password:
        file: secrets/wp_admin_password
    ftp-password:
        file: secrets/ftp-password

networks:
    inception:
        driver: bridge

volumes:
    db_data:
        name: db_data
        driver: local
        driver_opts:
            type: "none"
            device: ${HOME}/data/db
            o: "bind"

    wordpress_data:
        name: wordpress_data
        driver: local
        driver_opts:
            type: "none"
            device: ${HOME}/data/wp
            o: "bind"
